version: '3'
services:
  top.api:
    image: docker.io/4ebok/mydocker:latest
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
      